# Generated by Django 3.0.3 on 2020-07-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='fields',
            field=models.ManyToManyField(related_name='fields', through='form_generator.FormField', to='form_generator.Field'),
        ),
    ]
