# Generated by Django 3.0.3 on 2020-07-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='page',
            name='sections',
        ),
    ]
