# Generated by Django 3.0.3 on 2020-07-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0003_auto_20200729_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='form',
            field=models.ManyToManyField(related_name='formGroup', through='form_generator.GroupForm', to='form_generator.Form'),
        ),
    ]
