# Generated by Django 3.0.3 on 2020-07-31 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0004_auto_20200729_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sections',
        ),
    ]
