# Generated by Django 3.0.3 on 2020-08-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0005_remove_page_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='default_value',
        ),
        migrations.RemoveField(
            model_name='field',
            name='description',
        ),
        migrations.RemoveField(
            model_name='field',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='field',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='field',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='field',
            name='required',
        ),
        migrations.RemoveField(
            model_name='field',
            name='visible',
        ),
        migrations.AddField(
            model_name='formfield',
            name='default_value',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='enable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='label',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='max_value',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='min_value',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='placeHolder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='required',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='visible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='help_text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='form_generator.Field'),
            preserve_default=False,
        ),
    ]
