# Generated by Django 3.0.3 on 2020-08-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0006_auto_20200801_1956'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together=set(),
        ),
    ]
