# Generated by Django 3.0.3 on 2020-08-04 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0008_auto_20200803_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='form_generator.Form'),
        ),
        migrations.AlterField(
            model_name='pageform',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='form_generator.Page'),
        ),
        migrations.AlterField(
            model_name='pageform',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='form_generator.Section'),
        ),
    ]
