# Generated by Django 3.0.3 on 2020-08-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0009_auto_20200804_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='form_generator.Form'),
            preserve_default=False,
        ),
    ]
