# Generated by Django 3.0.3 on 2020-08-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0011_auto_20200808_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_choices',
            field=models.ManyToManyField(blank=True, null=True, related_name='field_choices', through='form_generator.ChoiceField', to='form_generator.Chioce'),
        ),
    ]
