# Generated by Django 3.0.3 on 2020-08-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0012_auto_20200808_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='field_choices',
        ),
        migrations.AddField(
            model_name='formfield',
            name='field_choices',
            field=models.ManyToManyField(blank=True, null=True, related_name='field_choices', through='form_generator.ChoiceField', to='form_generator.Chioce'),
        ),
        migrations.AlterField(
            model_name='choicefield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_generator.FormField'),
        ),
    ]
