# Generated by Django 3.0.3 on 2020-08-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0013_auto_20200809_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_choices',
            field=models.ManyToManyField(related_name='field_choices', through='form_generator.ChoiceField', to='form_generator.Chioce'),
        ),
    ]
