# Generated by Django 3.0.3 on 2020-08-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0014_auto_20200809_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form_generator.Page'),
        ),
    ]
