# Generated by Django 3.0.3 on 2020-08-10 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0015_auto_20200809_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_generator.FormField'),
        ),
    ]
