# Generated by Django 3.0.3 on 2020-09-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0020_auto_20200902_2328'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupform',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupform',
            name='form',
        ),
        migrations.RemoveField(
            model_name='groupform',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupForm',
        ),
    ]
