# Generated by Django 3.0.3 on 2020-09-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_generator', '0022_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='form_generator.Answer'),
            preserve_default=False,
        ),
    ]
