from rest_framework import status

INVALID_DATA = status.HTTP_400_BAD_REQUEST
INCOMPLETE_DATA = status.HTTP_400_BAD_REQUEST
SUCCEEDED_REQUEST = status.HTTP_200_OK
CREATED = status.HTTP_201_CREATED
DELETED = status.HTTP_204_NO_CONTENT
NOT_FOUND = status.HTTP_404_NOT_FOUND

